name: Linux spidev Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  BUILD_TYPE: Release
  PICO_SDK_PATH: "~/pico-sdk"

jobs:
  build-with-linux-spidev:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt install -y cmake gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libnewlib-arm-none-eabi python3 git tar build-essential
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -DUSE_SPIDEV=true -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
