name: Linux spidev Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  BUILD_TYPE: Release
  PICO_SDK_PATH: "~/pico-sdk"

jobs:
  build-with-bsd-spidev-aarch64:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt install -y cmake gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libnewlib-arm-none-eabi python3 git tar build-essential
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -DUSE_SPIDEV=true -DUSE_AARCH64_LINUX_CC=true -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  build-with-linux-spidev-arm:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt install -y cmake gcc-arm-linux-gnueabihf g++-13-arm-linux-gnueabihf libnewlib-arm-none-eabi python3 git tar build-essential
      - name: Create
        run: sudo ln -s /usr/bin/arm-linux-gnueabihf-g++-13 /usr/bin/arm-linux-gnueabihf-g++
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -DUSE_SPIDEV=true -DUSE_ARM_LINUX_CC=true -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}