name: Pico SDK Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  BUILD_TYPE: Release
  PICO_SDK_PATH: "~/pico-sdk"

jobs:
  build-with-pico-sdk:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi python3 git tar build-essential
    - name: Checkout Pico SDK
      run: git clone --depth 1 https://github.com/raspberrypi/pico-sdk.git ~/pico-sdk
    - uses: actions/checkout@v4
    - name: Ensure CMake cache is cleared
      run: rm -f CMakeCache.txt
    - name: Configure CMake
      run: cmake -DUSE_PICO_LIB=true -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
